### ISSUE TITLE
Turn off quickfix after select

### ISSUE THREAD

**Issue by huyvohcmc** [misterbuckley/vim-definitive#8]
After selecting one definition from the quickfix list, can we turn it off so that it doesn't show the list in the new file?

**Comment by NKBelousov** [comment]
Maybe add different shortcuts for opening with/without closing quickfix. Kind of like NerdTree does it: I can open split/vsplit, tab, etc. Really depends on the situation.

**Comment by misterbuckley** [comment]
@huyvohcmc I could add an option to do that, but since the quickfix list is used by more than just this plugin, I'd like to avoid altering its functionality too much if possible

@NKBelousov I like this idea, but since the search results are just populated into the quickfix list, I've got two options here:
1. I could add mappings for the quickfix window, but again, this would alter its functionality more than I want to for this plugin
2. Instead of using the quickfix window, I could do what nerdtree/fugitive/etc do and add a separate window/filetype for vim-definitive's search results, which would allow me to add whatever mappings I want to it without interfering with other vim functionality

Option 2 would be nice, but I'm not sure I want to go that far with this plugin at the moment, unless someone else wants to do it and make a PR :)

Honestly what I would probably suggest here is just adding your own mappings for the quickfix window. https://stackoverflow.com/questions/16743112/open-item-from-quickfix-window-in-vertical-split has an example of a mapping to do what you're looking for. There's also apparently a plugin that adds similar mappings: https://www.vim.org/scripts/script.php?script_id=4778

I appreciate the suggestions though!
